---
sidebar: sidebar 
permalink: ONTAP/choose-ontap-910-later.html 
keywords: choose ontap target version, ontap update recommendations, identify ontap target version, recommended version, benefits and risks or ONTAP version 
summary: ONTAPストレージ システムをアップグレードする前に、各ONTAPバージョンの利点とリスクを理解してください。 
---
= ONTAPのバージョンを比較して、ソフトウェアアップデートを使用するメリットとリスクを理解する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージ システムのONTAPバージョンを更新する前に、 ONTAPターゲット バージョンに関連する利点とリスクを比較して理解することが非常に重要です。

ターゲット バージョンを選択し、現在のバージョンと比較することで、 ONTAPで特定のバージョンに更新する利点を把握できます。また、特定のバージョンのONTAPに更新することで解決されるリスクと、発生する新しいリスク（ある場合）も確認できます。


NOTE: この機能は、 ONTAP 9.10 以降のバージョンを実行している場合にのみ使用できます。

.手順
. コンソールの左側のナビゲーションから、*正常性* > *ソフトウェア更新*を選択します。
+
ソフトウェアの更新が必要なクラスターのリストが表示されます。推奨されるターゲット バージョンに更新するか、別のバージョンを選択できます。



|===
| 状況 | 操作 


 a| 
推奨バージョンにアップデートしたい
 a| 
. *ターゲット バージョン* 列で、*バージョンの比較* をクリックして、推奨されるONTAPバージョンに更新した場合の機能上の利点とリスク上の利点を表示します。
. 解決されるリスク、引き続き残るリスク、および更新後に導入される新しいリスクに関する情報を選択して表示します。
. 必要に応じて、[更新プランのダウンロード] をクリックして、更新プランのコピーをダウンロードします。
. 更新プロセスを開始するには、[*更新を開始*] をクリックします。




 a| 
別のバージョンを選択する
 a| 
. *ターゲット バージョン* 列で、ドロップダウンをクリックし、*他のバージョンを選択* を選択します。
. 機能の利点とリスクの利点を表示するには、バージョンを選択します。
. 解決されるリスク、引き続き残るリスク、および更新後に導入される新しいリスクに関する情報を選択して表示します。
. 必要に応じて、[更新プランのダウンロード] をクリックして、更新プランのコピーをダウンロードします。
. 更新プロセスを開始するには、[*更新の開始*] を選択します。


|===