---
sidebar: sidebar 
permalink: ONTAP/fix-blockers-warnings.html 
keywords: fix ontap blockers and warnings, ontap update precheck, acknowledge warnings 
summary: ONTAPブロッキングを修正し、 ONTAP の更新の完了を妨げている警告を確認します。 
---
= ONTAP のアップグレード前にソフトウェア アップデートを使用してすべての障害を修正します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAPストレージ システムのONTAPターゲット バージョンを特定したら、 ONTAPストレージ システムを更新する前に、すべてのブロッキングを修正して確認し、警告を確認する必要があります。

ソフトウェアを更新する前に、すべてのブロッキングを修正して認識する必要があります。

.手順
. コンソールの左側のナビゲーションから、*正常性* > *ソフトウェア更新*を選択します。
+
コンソールには、ソフトウェアの更新が必要なクラスターのリストが表示されます。

. ストレージ システムのONTAPターゲット バージョンを識別します。  ONTAPターゲットバージョンの識別方法については、以下を参照してください。link:../ONTAP/choose-ontap-910-later.html["ONTAPのバージョンを比較して、ソフトウェアアップデートを使用するメリットとリスクを理解する"] 。
. ONTAP のターゲット バージョンを決定したら、[*更新の準備*] を選択して更新プロセスを開始します。
+
ブロッキングと警告のリストが表示されます。

. ブロッキングを修正するための手順を表示するには、ブロッキングを選択してください。
. 提供されている手順を手動で実行して、ブロッカーを修正します。
. 修正されたブロッカーを選択し、「*選択した項目を確認する*」を選択して、ブロッカーが修正されたことを確認します。



NOTE: 更新を続行するには、すべてのブロックを修正して確認する必要があります。

. ソフトウェアの更新を続行する前に、*警告*タブを選択して警告を確認してください。
. 修正されたブロッカーを表示するには、[*承認*] タブを選択します。
. 更新プロセスを続行するには、[*更新を続行*] を選択します。

