---
sidebar: sidebar 
permalink: get-started/software-updates.html 
keywords: ontap 9.10, ontap update, supported systems for ontap update, ontap version, software updates benefits 
summary: ソフトウェア アップデートを使用してONTAPストレージ システムをシームレスに更新し、新機能や拡張機能を活用します。 
---
= ソフトウェアアップデートについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ソフトウェア アップデートを使用すると、顧客がONTAPアップデートを効率化できるようになります。これにより、コストの削減、重要なワークロードの高速化、セキュリティの向上が可能になります。

ソフトウェアの更新により、評価、計画、実行のプロセスが自動化されます。インテリジェント アップグレード アドバイザーは、特定のシステムに最適なバージョンを予測し、問題を修正し、効率を改善し、システムのセキュリティを強化するバージョンを推奨して、顧客がニーズを満たす最適なオプションを決定できるようにします。次に、ソフトウェア パッケージを配布し、サポート サービスに依存せずに自動非配布アップグレード (ANDU) を自動的に実行します。



== NetAppコンソール

ソフトウェア アップデートには、 NetAppコンソールからアクセスできます。

NetAppコンソールは、オンプレミスとクラウド環境全体にわたるエンタープライズ グレードのNetAppストレージとデータ サービスの集中管理を提供します。NetAppデータ サービスにアクセスして使用するには、コンソールが必要です。管理インターフェースとして、1 つのインターフェースから多数のストレージ リソースを管理できます。コンソール管理者は、企業内のすべてのシステムのストレージとサービスへのアクセスを制御できます。

NetAppコンソールの使用を開始するためにライセンスやサブスクリプションは必要ありません。ストレージ システムまたはNetAppデータ サービスへの接続を確保するためにクラウドにコンソール エージェントを展開する必要がある場合にのみ料金が発生します。ただし、コンソールからアクセスできる一部のNetAppデータ サービスは、ライセンスまたはサブスクリプションベースです。

詳細はこちら https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["NetAppコンソール"]。



== サポートされているONTAPシステム

ONTAP 9.10 以降のバージョンを実行している場合にのみ、ソフトウェア更新を使用してONTAP の更新を完了できます。

次の情報は、さまざまなONTAPバージョンのソフトウェア更新プロセスを示しています。

|===
| *現在のONTAPバージョン* | *更新プロセス* 


| 9.12以上 | ONTAPアップデートのすべての手順はコンソール内で実行されます。 


| 9.10～9.12 | ONTAPアップデートの準備は、ソフトウェア アップデート画面内で行われます。実際のONTAPアップデートを実行するには、System Manager に移動します。コンソール内でONTAPアップデートのすべての手順を実行するには、link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html["コンソールエージェントを設定する"] 。 


| 9.8～9.10 | ONTAPアップデートの準備は、ソフトウェア アップデート画面内で行われます。実際のONTAPアップデートを実行するには、System Manager に移動します。 


| 9.7未満 | このクラスタでは自動ONTAP更新はサポートされていません。 ONTAP を手動で更新する必要があります。詳細については、以下を参照してください。 link:https://docs.netapp.com/us-en/ontap/upgrade/index.html["ストレージシステムを手動で更新する"] 。 
|===


== ソフトウェアアップデートを使用する利点

ONTAPストレージ システムを更新すると、ストレージ システムのパフォーマンス、セキュリティ、および機能が向上します。

ONTAPストレージ システムを更新すると、次のような利点があります。

* 新しいプロトコル、データ サービス、クラウド統合オプションなど、 ONTAPが提供する最新の機能と拡張機能にアクセスできます。
* システムの安定性、信頼性、セキュリティに影響を与える可能性のあるバグや脆弱性を修正できます。
* 最新のパッチと改善を適用することで、システムのパフォーマンスと効率を最適化できます。
* 他のNetApp製品、サードパーティ アプリケーション、クラウド プロバイダーとの互換性と相互運用性を確保できます。
* NetApp が最新のONTAP OS バージョンに対して提供する継続的なサポートとメンテナンスのメリットを享受できます。




== 料金

NetApp はソフトウェア アップデートの使用に対して料金を請求しません。
